// Textos fijos del manual en cada idioma (PLAN-SITIO.md S11): la plantilla,
// las fichas de la referencia y los avisos. Los títulos del índice están en
// indice.mjs y los de los parámetros en engine/opciones.js. Los mensajes de
// error del generador quedan en español: son para quien escribe el manual.

/** @typedef {'es' | 'en'} Idioma */

/** @type {Idioma[]} */
export const IDIOMAS = ['es', 'en'];

export const TEXTOS = {
  es: {
    manual: 'Manual',
    tituloManual: 'Manual de DarwinBots',
    descripcion: 'Manual de DarwinBots portado a WebAssembly.',
    bajada:
      'Cómo funciona DarwinBots en esta versión: la simulación, el lenguaje del ADN, cada sysvar y cada operador, tutoriales y la guía de la app.',
    indice: 'Índice',
    indiceAria: 'Índice del manual',
    buscar: 'Buscar en el manual',
    abrirApp: 'Abrir la app',
    tema: 'Tema',
    temaTitulo: 'Tema: sistema, claro u oscuro',
    migas: 'Migas',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    pie: 'DarwinBots 2.48.32 portado a WebAssembly',
    codigo: 'Código fuente',
    otroIdioma: 'English',
    otroIdiomaTitulo: 'This page in English',
    pendiente: 'pendiente',
    sinEscribir: 'Esta página todavía no está escrita.',
    sinTraducir: 'Esta página todavía no está escrita.',
    leerEnOtro: '',
    copiar: 'Copiar',
    datosSpec: 'Datos de la spec',
    fuente: 'Fuente en el original',
    direccion: 'Dirección',
    nombre: 'Nombre',
    nombres: 'Nombres',
    tipo: 'Tipo',
    grupo: 'Grupo',
    escribe: 'Quién la escribe',
    lee: 'Quién la lee',
    borra: 'Cuándo se borra',
    rango: 'Rango',
    nota: 'Nota',
    mutaciones: 'Mutaciones',
    /** @param {string} m */
    laEligen: (m) => `la eligen ${m}`,
    noLaEligen: 'no la eligen como objetivo',
    comoLectura: 'como lectura (<code>*</code>)',
    comoDestino: 'como destino de un store',
    y: ' y ',
    sysvar: 'Sysvar',
    resumen: 'Resumen',
    palabra: 'Palabra',
    alias: 'Alias',
    familia: 'Familia',
    pilaEntera: 'Pila entera',
    pilaBooleana: 'Pila booleana',
    /** @param {string} s @param {string} p */
    sacaPone: (s, p) => `saca ${s}, pone ${p}`,
    todo: 'todo',
    queHace: 'Qué hace',
    valor: 'Valor',
    costo: 'Costo',
    divisionCosto: 'División del costo',
    seEjecuta: 'Se ejecuta en',
    marcaLazos: 'Marca lazos',
    si: 'sí',
    no: 'no',
    operador: 'Operador',
    porDefecto: 'Por defecto',
    valores: 'Valores',
    rangoHabitual: 'Rango habitual',
    /** @param {number} a @param {number} b */
    deA: (a, b) => `${a} a ${b}`,
    siNo: 'sí / no',
    variable: 'Variable',
    clave: 'Clave',
    enVivo: 'En vivo',
    vivoSi: 'se puede cambiar con la simulación corriendo',
    vivoNo: 'requiere una simulación nueva',
    modo: 'Modo',
    modoBasico: 'básico y avanzado',
    modoAvanzado: 'solo avanzado',
    /** @param {number} d */
    tituloDireccion: (d) => `Dirección ${d}`,
    todasSysvars: 'Todas las sysvars',
    todosOperadores: 'Todos los operadores',
    /** @param {string} g */
    tituloParametros: (g) => `Parámetros: ${g}`,
    /** @param {string} f */
    resumenOperador: (f) => `Operador · ${f}`,
    sentidos: {
      cmd: ['Comando', 'el bot la escribe y el motor la lee y, en general, la consume'],
      sense: ['Sentido', 'el motor la escribe para que el ADN la lea'],
      bidi: ['Entrada y salida', 'la escriben el bot y el motor'],
      int: ['Interna', 'el motor la reescribe; escribirla no tiene efecto duradero'],
      free: ['Libre', 'tiene nombre, pero el motor no la usa'],
    },
  },
  en: {
    manual: 'Manual',
    tituloManual: 'DarwinBots manual',
    descripcion: 'Manual of DarwinBots ported to WebAssembly.',
    bajada:
      'How DarwinBots works in this version: the simulation, the DNA language, every sysvar and every operator, tutorials and the app guide.',
    indice: 'Contents',
    indiceAria: 'Manual contents',
    buscar: 'Search the manual',
    abrirApp: 'Open the app',
    tema: 'Theme',
    temaTitulo: 'Theme: system, light or dark',
    migas: 'Breadcrumbs',
    anterior: 'Previous',
    siguiente: 'Next',
    pie: 'DarwinBots 2.48.32 ported to WebAssembly',
    codigo: 'Source code',
    otroIdioma: 'Español',
    otroIdiomaTitulo: 'Esta página en español',
    pendiente: 'pending',
    sinEscribir: 'This page has not been written yet.',
    sinTraducir: 'This page has not been translated yet.',
    leerEnOtro: 'Read it in Spanish',
    copiar: 'Copy',
    datosSpec: 'Data from the spec',
    fuente: 'Source in the original',
    direccion: 'Address',
    nombre: 'Name',
    nombres: 'Names',
    tipo: 'Kind',
    grupo: 'Group',
    escribe: 'Written by',
    lee: 'Read by',
    borra: 'Cleared',
    rango: 'Range',
    nota: 'Note',
    mutaciones: 'Mutations',
    /** @param {string} m */
    laEligen: (m) => `picked ${m}`,
    noLaEligen: 'never picked as a target',
    comoLectura: 'as a read (<code>*</code>)',
    comoDestino: 'as a store target',
    y: ' and ',
    sysvar: 'Sysvar',
    resumen: 'Summary',
    palabra: 'Word',
    alias: 'Aliases',
    familia: 'Family',
    pilaEntera: 'Integer stack',
    pilaBooleana: 'Boolean stack',
    /** @param {string} s @param {string} p */
    sacaPone: (s, p) => `pops ${s}, pushes ${p}`,
    todo: 'all',
    queHace: 'What it does',
    valor: 'Value',
    costo: 'Cost',
    divisionCosto: 'Cost divisor',
    seEjecuta: 'Runs',
    marcaLazos: 'Marks ties',
    si: 'yes',
    no: 'no',
    operador: 'Operator',
    porDefecto: 'Default',
    valores: 'Values',
    rangoHabitual: 'Usual range',
    /** @param {number} a @param {number} b */
    deA: (a, b) => `${a} to ${b}`,
    siNo: 'yes / no',
    variable: 'Variable',
    clave: 'Key',
    enVivo: 'Live',
    vivoSi: 'can be changed while the simulation runs',
    vivoNo: 'needs a new simulation',
    modo: 'Mode',
    modoBasico: 'basic and advanced',
    modoAvanzado: 'advanced only',
    /** @param {number} d */
    tituloDireccion: (d) => `Address ${d}`,
    todasSysvars: 'All sysvars',
    todosOperadores: 'All operators',
    /** @param {string} g */
    tituloParametros: (g) => `Parameters: ${g}`,
    /** @param {string} f */
    resumenOperador: (f) => `Operator · ${f}`,
    sentidos: {
      cmd: ['Command', 'the bot writes it and the engine reads it and usually consumes it'],
      sense: ['Sense', 'the engine writes it for the DNA to read'],
      bidi: ['Input and output', 'both the bot and the engine write it'],
      int: ['Internal', 'the engine rewrites it; writing it has no lasting effect'],
      free: ['Free', 'it has a name, but the engine does not use it'],
    },
  },
};
